### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by ihenvyr** [LoicMahieu/react-styled-flexboxgrid#11]
Hi! Thank you for creating this useful component.

There's a problem though, it doesn't render the Grids, Row and Col correctly compared to other component in the page that also uses styled-components (rendered correctly when printing).

**Comment by LoicMahieu** [comment]
Hi! Do you have a code sample demonstrating the problem ?

**Comment by LoicMahieu** [comment]
I am cleaning issues. Please re-open it if you consider the problem is still present. Thanks.
