### ISSUE TITLE
Order of attributes xs and sm matter?

### ISSUE THREAD

**Issue by thongly** [LoicMahieu/react-styled-flexboxgrid#160]
It seems that 

```        
<Row>
    <Col xs={6} sm={4}>
        <img src="https://placehold.it/100x50" />
    </Col>
    <Col xs={6} sm={4}>
        <img src="https://placehold.it/100x50" />
    </Col>
    <Col xs={6} sm={4}>
        <img src="https://placehold.it/100x50" />
    </Col>
</Row>
```

is not the same as

```        
<Row>
    <Col sm={4} xs={6}>
        <img src="https://placehold.it/100x50" />
    </Col>
    <Col sm={4} xs={6} >
        <img src="https://placehold.it/100x50" />
    </Col>
    <Col sm={4} xs={6}>
        <img src="https://placehold.it/100x50" />
    </Col>
</Row>
```

Is this by design?

**Comment by LoicMahieu** [comment]
Hi @thongly 
No, props order should not affect the media queries that are generated.
Dimension props are sorted here: https://github.com/LoicMahieu/react-styled-flexboxgrid/blob/master/src/components/Col.js#L29

I don't see differences in theses examples, see: https://codesandbox.io/s/9o053mwlrp

**Comment by LoicMahieu** [comment]
Yes, indeed old versions are affected by this buggy behavior. Feel free to reopen the issue if you encounter this problem with current version.
