### ISSUE TITLE
3.0 in npm?

### ISSUE THREAD

**Issue by mmcc** [LoicMahieu/react-styled-flexboxgrid#165]
During an upgrade and using `yarn outdated` a lot, I noticed that this project has a 3.0 released on `npm` 2 months ago, but I can't find _anything_ about that release in the Github repo. Master still shows `2.6.0`, there's no `3.0` tag, branch, nothing. Was that an accidental release or something folks should actually be using?

**Comment by LoicMahieu** [comment]
Hi @mmcc 
Oops, forgot to push to Github ;)
Fixed!
Thanks
