### ISSUE TITLE
Why is gutter dependent on fluid setting?

### ISSUE THREAD

**Issue by mschipperheyn** [LoicMahieu/react-styled-flexboxgrid#19]
I want to use a gutter in the normal grid setting (specified width), but I see in the code that `fluid` is required to use a gutter. I wonder why that is?

**Comment by LoicMahieu** [comment]
Mmh... Not sure... I followed flexboxgrid.css. I need to take a look but I don't have enough time now ;) Feel free to send a PR

**Comment by misund** [comment]
If someone is here looking for a workaround, you can try something like this: https://github.com/dbmedialab/shiny/blob/master/src/atoms/Grid.js

**Comment by misund** [comment]
I seems that this issue (outerMargins only being applied to fluid grids) is affecting many users.

@LoicMahieu Will you consider merging #87 to fix this issue?
