### ISSUE TITLE
Using SC's attrs passes down non-DOM props

### ISSUE THREAD

**Issue by aaronmcadam** [LoicMahieu/react-styled-flexboxgrid#25]
Hi there, thanks for a great library!

With `styled-components` v2, there's [a new `attrs` API](https://github.com/styled-components/styled-components/pull/365) that simplifies wrapping third-party components.

However, wrapping one of `react-styled-flexboxgrid`'s components, for example `Col`, raises:

```
Warning: Unknown prop `theme` on <div> tag. Remove this prop from the element
```

Here's the gist: https://gist.github.com/aaronmcadam/52b5d1f93d472ce5f33738c8f52b76ed

**Comment by aaronmcadam** [comment]
If we replace [this sort of logic](https://github.com/LoicMahieu/react-styled-flexboxgrid/blob/master/src/components/Grid.js#L8) with `styled.div`, it might work.

If we need to use another tag name, we can call `.extendWith('section')()` on it

**Comment by LoicMahieu** [comment]
Hi

Thanks to point me the `.attrs()` method. It looks powerful.
But at this time the v2 is not yet stable. We could maintain a side branch, like `next`. Are you interested to make a PR for support v2 ?

**Comment by aaronmcadam** [comment]
It's at RC now, so it's nearly ready. I could try a PR but just using attrs won't fix this I think. I think extend or extendWith is what we should be usingOn 8 May 2017 18:41, Loïc Mahieu <notifications@github.com> wrote:Hi
Thanks to point me the .attrs() method. It looks powerful.
But at this time the v2 is not yet stable. We could maintain a side branch, like next. Are you interested to make a PR for support v2 ?

**Comment by aaronmcadam** [comment]
[v2 has been officially released.](https://medium.com/styled-components/announcing-v2-f01ef3766ac2) Did you have any ideas on how we might fix this issue @LoicMahieu?

**Comment by LoicMahieu** [comment]
Houra! 🎉

I suppose that if we just remove the support for `tagName` prop, we could simply use a `styled.div` and... done ?

**Comment by aaronmcadam** [comment]
That would be the fastest fix and then we could look at supporting custom tags later, maybe using the `withComponent` method.

**Comment by aaronmcadam** [comment]
Thanks for sorting this! :heart:
