### ISSUE TITLE
Non fluid Grid outer_margin is not applied. Is this intentional?

### ISSUE THREAD

**Issue by erwagasore** [LoicMahieu/react-styled-flexboxgrid#31]
I noticed that `outer_margin` is not applied on `<Grid></Grid>` this becomes an issue on a extra small dimension `xs` since content touches the edges of the window. See image below on the bottom

![screen shot 2017-04-26 at 1 26 51 am](https://cloud.githubusercontent.com/assets/1290048/25411853/7ec6c748-2a1f-11e7-9bfd-1addc3a00977.png)

**Comment by LoicMahieu** [comment]
Hi
I don't see the problem on demo. Could you please paste a code sample ? Thanks.

**Comment by LoicMahieu** [comment]
I am cleaning issues. Please re-open it if you consider the problem is still present. Thanks.
