### ISSUE TITLE
Error with React v15.5.4 - PropTypes Deprecated

### ISSUE THREAD

**Issue by miguelcast** [LoicMahieu/react-styled-flexboxgrid#32]
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by purplecones** [comment]
Please merge https://github.com/LoicMahieu/react-styled-flexboxgrid/pull/29 so that this issue can be resolved.

**Comment by LoicMahieu** [comment]
Thanks guys. v1.1.0
