### ISSUE TITLE
The 'md' 'lg' properties do not work in the Col component

### ISSUE THREAD

**Issue by miguelcast** [LoicMahieu/react-styled-flexboxgrid#52]
I made an update of the module to the last version, and the properties md and lg do not work in the Col component.

`<Col xs={12} sm={4} md={4} lg={2}>`
` <ItemList {...process} />`
`</Col>`

**Comment by millersdev** [comment]
The problem seems to be affected by the .sort() function in this commit; https://github.com/LoicMahieu/react-styled-flexboxgrid/commit/7089c3f421a12ab42b5408b921435c157272f76b

I can remove this function but no idea why this sort was added, any ideas?

**Comment by LoicMahieu** [comment]
Thanks for reporting!

Sort has been introduced for fix #44 . It would like that prop order does not impact rendering. I appears that dimensions iteration was from lower to higher instead of the inverse.
PR #56 should fix the problem.

**Comment by LoicMahieu** [comment]
+ react-styled-flexboxgrid@2.0.2

**Comment by millersdev** [comment]
Still not working.. Can you confirm this?

**Comment by miguelcast** [comment]
Not working, too

**Comment by LoicMahieu** [comment]
Indeed... Brokes my project too... Grrr... Working on it

**Comment by LoicMahieu** [comment]
+ react-styled-flexboxgrid@2.0.3

Sorting wasn't correct. Now it should be ok.

**Comment by miguelcast** [comment]
It works correctly in my project, thanks!
