### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by CruelMoney** [LoicMahieu/react-styled-flexboxgrid#59]
Is it possible to do server side rendering? 
I've tried using the methods documented [here](https://www.styled-components.com/docs/advanced#server-side-rendering) , but the returned elements are empty.

**Comment by mschipperheyn** [comment]
I have no problems using styled-components@2.0.0-15. However, there is an open bug with styled components for any version after that.

**Comment by LoicMahieu** [comment]
I have no problem too. This package rely on styled-components for that. Make sure you use styled-components@2. If you follow the document, it should works ;)

Extra quick snippet™:
```js
const sheet = new ServerStyleSheet()
const app = <App />
const body = renderToString(sheet.collectStyles(app))
const doc = renderToString(
  <html>
    <head>
      {sheet.getStyleElement()}
    </head>
    <body>
      {body}
    </body>
  </html>
)
```

**Comment by CruelMoney** [comment]
Thanks guys, downgrading from 2.1.0 to 2.0.15 helped.
