### ISSUE TITLE
Is there a possibility to add style via "className" to <Row> or <Col>? 

### ISSUE THREAD

**Issue by MaximusDesign** [LoicMahieu/react-styled-flexboxgrid#73]
See title

**Comment by LoicMahieu** [comment]
All components are simple `styled-components`. So for example, if you add a `className` to a `Row` component, it will be concatenated with the generated `className`.

Example:

```jsx
<Row className='foo'>
     {/* ... */}
</Row>
```

will produce something like this:

```html
<div class="Row__Row-kNtYPA bvOcuL foo">
     ...
</div>
```
