### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by romseguy** [LoicMahieu/react-styled-flexboxgrid#8]
Hey,

I came across a very similar project here https://github.com/JSBros/hedron ; wouldn't it be nicer to merge efforts? Or am I missing a difference in intent?

**Comment by LoicMahieu** [comment]
Hi!

Oh, I didn't know about `hedron` before coding `react-styled-flexboxgrid`. It seems a good alternative!

I don't think a "merge" could happen for theses 2 totally differents repos ;) But I could at least reference this project in the README.

Thanks
