### ISSUE TITLE
outerMargin 0 cause scrolling on mobile

### ISSUE THREAD

**Issue by igoldny** [LoicMahieu/react-styled-flexboxgrid#84]
if you set outerMargin to 0 and resize the browser to mobile breakpoint it causes scrolling.

Steps to reproduce:
1. enter: https://loicmahieu.github.io/react-styled-flexboxgrid/demo/index.html
2. set outerMargin = 0
3. resize browser

**Comment by misund** [comment]
To be more precise: You'll have horizontal scrolling if the outerMargin is less than half a gutterWidth.

I'm not sure if this is a bug or a feature, actually.

**Comment by igoldny** [comment]
definitely, feature sounds useful :)
anyways I use this workaround:

`
const RowSystem = styled(StyledRow)`
  @media (max-width: ${media.sm}) {
    margin-left: 0;
    margin-right: 0;
  }
`;

const ColSystem = styled(StyledCol)`
  @media (max-width: ${media.sm}) {
    padding-right: 0;
    padding-left: 0;
  }
`;
`

**Comment by LoicMahieu** [comment]
If @misund is right, we could calculate if the outerMargin is less than half a gutterWidth and in this case ?
