### ISSUE TITLE
peer dependency

### ISSUE THREAD

**Issue by Dominic-Preap** [LoicMahieu/react-styled-flexboxgrid#89]
Hi, This is not an issue but a request. Could you update your peer dependency?
`react-styled-flexboxgrid@2.1.1" has unmet peer dependency "prop-types@^15.6.0".`

Thanks,

**Comment by dphrag** [comment]
There's nothing to update. If you're referring to that message appearing, peer dependencies aren't installed automatically, so you can get rid of the message by adding prop-types to your package.json. 15.6 is the latest prop-types.

**Comment by Dominic-Preap** [comment]
After adding prop-types in package.json, still show the same message. Maybe he is still using` prop-types@^15.0.0-0`.

**Comment by dphrag** [comment]
No that's really not the case.
