### ISSUE TITLE
Remove text-align

### ISSUE THREAD

**Issue by Dremora** [LoicMahieu/react-styled-flexboxgrid#90]
Currently setting a `center` or `end` property on `Row` also sets `text-align`. This property is not responsible for the layout (that's what `justify-content` is for), but what's worse, it gets inherited by all children, causing unwanted effects. I still expect text to be left-aligned even when containing column is aligned to the right.

**Comment by LoicMahieu** [comment]
Hi @Dremora 
Thanks for sharing your experience.

Yes I make sense that `Row` should not change text alignement. It was based on the behavior of `flexboxgrid.css`.
