### ISSUE TITLE
Unable to run Demo

### ISSUE THREAD

**Issue by dmk255** [LoicMahieu/react-styled-flexboxgrid#96]
Hello!

I'm attempting to run the demo for this project locally but have been having trouble with the dependencies. I believe there are conflicting versions of `react-dom` and `react` in use. The specific error is:
```
react-dom.development.js:833 Uncaught TypeError: Cannot read property 'ReactCurrentOwner' of undefined
```

reproduction steps:
```
git clone git@github.com:LoicMahieu/react-styled-flexboxgrid.git
cd react-styled-flexboxgrid
npm install
npm install styled-components@2
npm install  react@^16.0.0-0
npm install prop-types@^15.0.0-0
npm start
```
Go to http://localhost:8080

I've taken the dependencies listed above from the README.md. If I should be using a different set of peer dependencies please let me know!

**Comment by misund** [comment]
:point_up: Does that fix your problem?

**Comment by LoicMahieu** [comment]
Should be fixed now. Re-open if you encounter the problem again.
